In [1]:
import numpy as np
import models as mdl
import plots as plt

In [2]:
pred = np.arange(10)
actu = np.arange(10,20)

mdl.cvrmse(pred, actu)

0.68965517241379315

In [4]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(pred, actu)) / np.mean(actu)

0.68965517241379315

In [6]:
actu = actu - 15

In [7]:
actu

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [8]:
actu==0

array([False, False, False, False, False,  True, False, False, False, False], dtype=bool)

In [9]:
actu[actu!=0]

array([-5, -4, -3, -2, -1,  1,  2,  3,  4])